#!/usr/bin/env python2

import optparse
import os

from config import *

def main():
    """Runs program and handles command line options"""
    usage = optparse.OptionParser(description=' Leave the current Session',
                              prog='pylogout',
                              version='pylogout 0.1',
                              usage='%prog [OPTIONS]')

    usage.add_option('-S', '--screenlock', action ='store_true', help='Lock the screen')
    usage.add_option('-l', '--logout', action='store_true', help='Close open programs and logout')
    usage.add_option('-s', '--suspend', action='store_true', help='Lock the screen and suspend')
    usage.add_option('-b', '--hibernate', action='store_true', help='Lock the screen and hibernate')
    usage.add_option('-r', '--reboot', action='store_true', help='Close open programs and reboot')
    usage.add_option('-p', '--poweroff', action='store_true', help='Close open programs and poweroff')

    options, arguments = usage.parse_args()

    if options.screenlock:
        os.system(lock_command)
    elif options.logout:
        os.system(close_command)
        os.system(logout_command)
    elif options.suspend:
        os.system(lock_command)
        os.system(suspend_command)
    elif options.hibernate:
        os.system(lock_command)
        os.system(hibernate_command)
    elif options.reboot:
        os.system(close_command)
        os.system(reboot_command)
    elif options.poweroff:
        os.system(close_command)
        os.system(shutdown_command)
    else:
        usage.print_help()

if __name__ == '__main__':
    main()
